### PR TITLE
gradle migration

### PR DESCRIPTION
**Pull request by josecmarcucci005**
Hi, I just found your project which I really like by the way :-) and made an small migration from maven to gradle which I think is a nice feature. Of course if you don't agree feel free to decline the pull request.

Cheers!

### CODE REVIEW

**Comment by activey** [comment]
Hmm, haven't considered it before, will get back to you ;)

**Comment by activey** [comment]
I'd like to ask you to do some tests before I accept this pull request, ok? I've never used gradle before on that scale and I'm just not 100% sure if it will provide the same subset of features as maven did.

**Comment by josecmarcucci005** [comment]
Maybe is a good idea to keep both versions... there are a lot of developer which still preferring maven but technically speaking gradle should provide all what maven does and much more. 
Anyway if you agree, I will cancel the pull request and keep the gradle version in separated branch by now.
I also have deployed to heroku the licket-demo :-) and works like a charm 

https://agile-lowlands-68305.herokuapp.com

I am really amazed how simple and stable licket is, it's simplicity remains me a bit rubyOnrails but in fast :-D  you did a really good job!

**Comment by activey** [comment]
Hey, I appreciate you like it :) I put quite much effort to make it as simple as possible :)
And yes, I would rather keep gradle version on a separate branch for now, will see how it will play ...
Cheers, and feel free to participate! :)

**Pull request closed without merging**
